theoraccoon/amby-craft-be

package-lock.json
package.json

Created initial folder and file structure for Google authentication using Passport and the CQRS pattern. Includes placeholders for command, handler, query, strategy, service, controller, and optional route file.

feat(google-auth): scaffold module with CQRS structure for Google SSO

---

prisma/migrations/20250428160346_add_course_lesson_lessontype_content_models/migration.sql
prisma/schema.prisma
src/config/constants.ts

- Add content, lesson, lesson-type and course models
- Add various block types

feat: add other models

---

prisma/migrations/20250429103951_refresh_token_user/migration.sql
prisma/schema.prisma
src/app.module.ts
src/users/dto/create-user.dto.ts
src/users/dto/update-user.dto.ts
src/users/entities/user.entity.ts
src/users/users.controller.spec.ts
src/users/users.controller.ts
src/users/users.module.ts
src/users/users.service.spec.ts
src/users/users.service.ts

Implemented basic CRUD operations for the `User` entity using a generic service/controller pattern.
This change lays the groundwork for user management in the system. Having a standard CRUD setup allows for faster development and easier maintenance as more user-related features are added.
- Created a generic CRUD service and controller structure.
- Applied the pattern to the `User` model, including create, read, update, and delete endpoints.
- Integrated with the existing routing/module system.
- Added basic input validation and error handling.
```markdown
[tasklist]
```

chore: add generic  user crud

---

src/app.module.ts
src/auth/auth.controller.spec.ts
src/auth/auth.controller.ts
src/auth/auth.module.ts
src/auth/auth.service.spec.ts
src/auth/auth.service.ts

✅ **What changed**
Generated boilerplate code for the sign-up feature using the NestJS CLI.
🧠 **Why it changed**
Scaffolding the module, service, and controller sets up the foundation for implementing the sign-up logic in a clean, modular structure.
🔧 **How it was implemented**
* Ran NestJS CLI commands to generate the `Auth` module.
* Created `AuthService` and `AuthController` for handling future sign-up logic.
* No business logic added yet — structure only.
📋 **Tasklist**

chore: add genereric auth logic

---

src/auth/dto/create-user.dto.ts
src/auth/dto/login.dto.ts

chore(clean ups): minor formatting clean ups and linting

---

.dockerignore
.gitignore
Dockerfile
docker-compose.yml
src/app.module.ts
src/auth/auth.module.ts
src/auth/google/google-auth.controller.ts
src/auth/google/google-auth.module.ts
src/auth/strategies/google.strategy.ts
src/modules/course/commands/create-course.command.ts
src/modules/course/commands/handlers/create-course.handler.ts
src/modules/course/course.controller.ts
src/modules/course/course.module.ts
src/modules/course/dto/create-course.dto.ts

**What changed**
* Introduced a CQRS-based architecture for managing course-related operations.
* Added Prisma models for `Course`, `Lesson`, `Block`, and `Author`.
* Created commands, handlers, and DTOs for course creation and block management.
* Implemented `@nestjs/cqrs` module integration.
**Why it changed**
* To provide scalable and maintainable architecture with separation of command/query responsibilities.
* Ensures modular handling of course creation and content manipulation with potential for event-driven expansion.
**How it was implemented**
* Used `@nestjs/cqrs` to structure command handlers and dispatchers.
* Commands: `CreateCourseCommand`, `AddBlockToLessonCommand`.
* Queries: To be implemented in subsequent PRs.
* DTOs validated using class-validator.
* Used …

chore(course): course creation clean ups

---

src/config/lang/de.json

Converted English in en.json to German in de.json for internationalization

chore(lang): converted en.json in english to de.json(german)

---

src/app.module.ts
src/config/constants.ts

chore(i18n): update constants

---

src/app.controller.ts
src/common/config/swagger.config.ts
src/modules/auth/google/google-auth.module.ts
src/modules/auth/strategies/google.strategy.ts
src/modules/lesson/lesson.module.ts
src/modules/users/users.module.ts

Update some invalid imports for files

fix: correct wrong file imports

---

src/modules/block/block.controller.ts
src/modules/block/commands/create-block.command.ts
src/modules/block/commands/handlers/create-block.handler.ts
src/modules/block/dto/create-block.dto.ts
src/modules/block/queries/get-all-blocks.query.ts
src/modules/block/queries/get-block-by-id.query.ts
src/modules/block/queries/handlers/get-all-blocks.handler.ts
src/modules/block/queries/handlers/get-block-by-id.handler.ts

Add functionality to create and retrieve blocks using commands and queries in the application. This includes the necessary DTOs, command handlers, and controller methods to support these operations.

feat(block): implement create and get block functionality

---

docker-compose-dev.yml
src/app.module.ts
src/modules/block/block.module.ts

Introduce the BlockModule, including CQRS handlers and a controller for managing blocks. This enhances the application's modularity and functionality.

feat(block): add BlockModule with CQRS handlers and controller

---

src/modules/auth/basic/auth.controller.ts
src/modules/auth/basic/auth.module.ts
src/modules/auth/basic/auth.service.ts
src/modules/auth/basic/commands/signout.command.ts
src/modules/auth/basic/handlers/signout.handler.ts

71 feature create user sign out

---

src/modules/block/block.controller.ts
src/modules/course/courses.controller.ts

Introduce a new endpoint in the BlocksController to retrieve all blocks, enhancing the API functionality. Adjustments made to the CoursesController for consistency in endpoint structure.

feat(block): add endpoint to retrieve all blocks

---

src/modules/auth/basic/auth.controller.ts
src/modules/auth/basic/auth.module.ts
src/modules/auth/basic/handlers/refresh-token.handler.ts
src/modules/auth/basic/queries/refresh-token.ts

Refactored the Basic Auth logic to follow the CQRS (Command Query Responsibility Segregation) pattern using dedicated work handlers.
The previous implementation mixed responsibilities and was difficult to scale or test. By separating commands and queries, the logic becomes more maintainable, testable, and consistent with the architecture used in other modules.
* Extracted command and query logic into separate handler classes
* Updated the authentication flow to route through the appropriate handlers
* Ensured compatibility with existing login and token validation processes
* `type:enhancement`
* `area:api`
Checklist

chore: refactor basic auth to cqrs work handlers

---

src/modules/course/courses.controller.ts
src/modules/course/queries/get-all-courses.query.ts
src/modules/course/queries/handlers/get-all-courses.handler.ts

- Remove auto loaded lessons and blocks from courses
- Add user authorization to fetch courses

feat: add author to fetch courses

---

prisma/migrations/20250513123137_init/migration.sql
prisma/schema.prisma
src/modules/lesson/commands/handlers/update-lesson.handler.ts
src/modules/lesson/commands/update-lesson.command.ts
src/modules/lesson/dto/update-lesson.dto.ts
src/modules/lesson/lesson.controller.ts
src/modules/lesson/lesson.module.ts

- Implemented `UpdateLessonHandler` to handle lesson updates with proper validation and exception handling.
- Updated `LessonsController` to include:
- `getAllLessons` method for fetching all lessons.
- `createLesson` method for creating a new lesson.
- `updateLesson` method for updating a lesson with user authorization.
- Integrated `GetAllLessonsQuery` for fetching all lessons.
- Add validation decorators to `UpdateLessonDto` for better data integrity.
- Implement logging in `UpdateLessonHandler` for better debugging and monitoring.
- Add pagination support to `getAllLessons` for handling large datasets.
- Write unit tests for `LessonsController` and `UpdateLessonHandler` to ensure code quality.
- Enhance API documentation with Swagger decorators.
- Use a centralized authorization …

feat(lesson): implement update lesson endpoint

---

src/config/config.schema.ts
src/modules/auth/basic/services/auth.service.ts
src/modules/auth/strategies/google.strategy.ts
src/modules/auth/strategies/jwt.strategy.ts
src/modules/auth/types/index.ts

This PR introduces several updates and improvements to the authentication module. The key changes include refactoring services, strategies, and types, along with the removal of an unused file. These changes aim to enhance the maintainability and readability of the codebase.
---
- **`src/config/config.schema.ts`:** Deleted as it was no longer being used.
- **Modified Parameters:**
- Updated `configService` declaration by removing redundant trailing commas.
- **Functionality Update:**
- Updated `where` clause in the `findUnique` method:
- Changed `payload.userId` to `payload.sub`.
- **Parameter Adjustments:**
- Changed `configService` to a non-readonly parameter.
- Retained `googleAuthService` as a `private readonly` parameter.
- **Code Simplification:**
- Removed `EnvConfig` type from …

chore(auth): update jwt payload and removed config.schema

---

src/modules/course/courses.controller.ts
src/modules/course/queries/get-course-by-id.query.ts
src/modules/course/queries/handlers/get-course-by-id.handler.ts

- Added authorization to fetching a  course.
- Limited loaded data for a course to only lessons

feat: add authorization to fetch course

---

src/modules/block/block.controller.ts
src/modules/block/block.module.ts
src/modules/block/commands/handlers/update-block.handler.ts
src/modules/block/commands/update-block.command.ts
src/modules/block/dto/update-block.dto.ts

This PR introduces the functionality to update a block within the system. It includes the addition of a new endpoint, service logic, and necessary data transfer objects (DTOs) to handle block updates. The update operation ensures proper authorization and validation to maintain data integrity and security.
1. **Controller Updates**:
- Added a `PATCH /blocks/:id` endpoint in `BlocksController` to handle block updates.
- Ensured the endpoint uses `AuthGuard` for JWT-based authentication.
- Utilized `UpdateBlockDto` for request validation and data transfer.
2. **Command and Handler**:
- Introduced `UpdateBlockCommand` to encapsulate update block logic.
- Added `UpdateBlockHandler` to process the update command:
- Validates block existence.
- Ensures the user is authorized to update the block. …

feat(blocks): implement update bloks endpoint

---

src/modules/block/block.controller.ts
src/modules/block/commands/create-block.command.ts
src/modules/block/commands/handlers/create-block.handler.ts
src/modules/block/dto/create-block.dto.ts

- Added authorization to `create block` functionality
- Reordered existing blocks after create
- Update DTO to require Objects instead of strings for the `content` field

feat: add authorization to "create block" functionality

---

docker-compose-prod.yml
src/common/utils/auth.utils.ts
src/modules/auth/auth.controller.ts
src/modules/auth/auth.module.ts
src/modules/auth/commands/handlers/google-auth-command.handler.ts
src/modules/auth/commands/handlers/index.ts
src/modules/auth/commands/handlers/logout-user-command.handler.ts
src/modules/auth/commands/logout-user.command.ts
src/modules/auth/strategies/google.strategy.ts

Streamline the authentication process by renaming commands and enhancing user session management utilities. Introduce a new utility class for handling authentication cookies and redirect URLs. Update the Google authentication strategy to improve error handling and logging.

refactor(auth) process and improve session management

---

src/modules/auth/strategies/google.strategy.ts

- Refactored `GoogleStrategy` to:
- Use environment-based scopes for Google authentication, allowing dynamic configuration via `GOOGLE_AUTH_SCOPES`.
- Add a logger for better traceability and debugging of authentication issues.
- Improve error handling in the `validate` method, logging errors and returning a localized unauthorized exception on failure.
- Ensure all required Google OAuth config values are read from environment variables with safe defaults.
- To make Google OAuth scope configuration more flexible and environment-driven.
- To provide better error visibility and easier debugging through structured logging.
- To enhance security and user experience by returning clear, localized error messages on authentication failure.
- To ensure the authentication strategy is robust and …

chore(google): add prompt select-account
